DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  id INTEGER PRIMARY KEY, 
  title TEXT, body TEXT, image TEXT, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER TIMESTAMP_UPDATE BEFORE UPDATE ON posts BEGIN
  UPDATE posts SET update_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;